export {
  BASE_GRANT_AMOUNT,
  KIOSK_HEARTBEAT_MS,
  KIOSK_PRESENCE_TTL_MS,
  MAX_CHARGE_AMOUNT,
  MAX_ORDER_QUANTITY,
  MAX_PRODUCT_PRICE,
  MAX_TRANSACTION_AMOUNT,
  PAIRING_TTL_MS,
  PAYMENT_TTL_MS,
} from "@flick/contract";
